#ifndef QT3DWIDGET_GLOBAL_H
#define QT3DWIDGET_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(QT3DWIDGETLIB_LIBRARY)
#  define QT3DWIDGETLIB_EXPORT Q_DECL_EXPORT
#else
#  define QT3DWIDGETLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // QT3DWIDGET_GLOBAL_H
